apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhoai-chatbot-demo 
  janus-idp.io/tekton: rhoai-chatbot-demo
  backstage.io/kubernetes-id: rhoai-chatbot-demo
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhoai-chatbot-demo
resources: 
- application-dev.yaml