---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rhoai-chatbot-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhoai-chatbot-demo 
  name: rhoai-chatbot-demo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi